### ISSUE TITLE
Uninitialized constant User::Counter

### ISSUE THREAD

**Issue by mhluska** [cedric/custom_counter_cache#25]
I'm seeing this error when deploying to Heroku production but not in development. I'm having a hard time debugging it. Just thought I'd let you know in case you've seen this before.

I've added `include CustomCounterCache::Model` to the top of the User model. Then I've added

```
  define_counter_cache :videos_published_count do |user|
    user.videos_published.count
  end
```

The migration:

```
class AddVideosPublishedCountToUsers < ActiveRecord::Migration[5.1]
  def change
    add_column :users, :videos_published_count, :integer, :default => 0, :null => false

    User.reset_column_information
    User.find_each do |u|
      User.update_counters(u.id, videos_published_count: u.videos_published.length)
    end
  end
end
```

The only reference to `Counter` I can find in the codebase is in the test directory so it's not making sense.

**Comment by atitan** [comment]
I just ran into the same issue.

It checks whether the current model has the right column, otherwise use Counter model.
This check is executed when Rails autoloads but migration hasn't begun at that time.
That's why it will want to use Counter model that does not exist.

```
unless column_names.include?(cache_column.to_s)
  has_many :counters, as: :countable, dependent: :destroy
end
```
https://github.com/cedric/custom_counter_cache/blob/master/lib/custom_counter_cache/model.rb#L11

**Comment by cedric** [comment]
I don't have time to look into this ATM, but splitting-up it up into a schema change and a data migration might work. I'm guessing that the User model needs to be reloaded before updating the couters?
